### ISSUE TITLE
eval("string") does not parse

### ISSUE THREAD

**Issue by haukex** [xsawyerx/guacamole#106]
As the title says, Guacamole appears to only know about `eval BLOCK`, not `eval(STRING)`. `eval { die() };` parses, `eval("1+2");` does not. If this is intentional, then it should probably be documented in `standard.pm`.

Not sure if related, but `eval {};` fails to parse as well.

**Comment by xsawyerx** [comment]
Thank you for spotting it!

**Comment by xsawyerx** [comment]
Fixed in 0.007, just released.

**Comment by haukex** [comment]
Thank you!
