### ISSUE TITLE
Remove dependency on Path::Tiny

### ISSUE THREAD

**Issue by wollmers** [xsawyerx/guacamole#121]
`Path::Tiny` isn't tiny anymore. Just for slurping a file it's a little bit oversized to pay the prize for the dependencies:

https://github.com/dagolden/Path-Tiny/issues/248
https://github.com/Dual-Life/digest/issues/9

**Comment by xdg** [comment]
Path::Tiny has no non-core dependencies and the core dependency versions specified are provided by every Perl from the 5.12 release in 2010.

**Comment by wollmers** [comment]
Close it as very minor problem.
