### ISSUE TITLE
Define "Standard Perl"

### ISSUE THREAD

**Issue by briandfoy** [xsawyerx/guacamole#87]
What makes some code "standard" and others not? What Perl don't I get to use if I want to use guacamole?

**Comment by briandfoy** [comment]
So, what is the standard? What do you allow and what do you disallow? That's the definition I'm after.

**Comment by xsawyerx** [comment]
It's on the wiki and it should be added to the POD. It is also my hope to see a book on it. :)

**Comment by briandfoy** [comment]
Closing in favor of #93

**Comment by xsawyerx** [comment]
Documentation added in this PR: https://github.com/xsawyerx/guacamole/pull/96.
