### ISSUE TITLE
Alternate regexp delimiters trigger a warning

### ISSUE THREAD

**Issue by scottchiefbaker** [xsawyerx/guacamole#89]
Consider the following code to remove `https://` from a string

    my $str = "https://google.com";

    # Triggers a warning (but is must more readable)
    $str =~ s|https://||;

    # No warning, but a lot harder to read
    $str =~ s/https:\/\///;

I think alternate regexp delimiters should be considered standard. At least some primary chars like: `|`, `/`, `!', and maybe `@` should be OK.

**Comment by rabbiveesh** [comment]
If you're making a list of quote delimiters, {} should be supported too.

**Comment by scottchiefbaker** [comment]
I dunno why but I've always used `|` as an alternate delimiter. it's not a huge deal breaker though. I can switch to `!`.

Not really clear what this means:

> I'm not a fan because it's a fairly distance character for non-Perl devs who aren't used to other Perl devs using it

**Comment by jeffreykegler** [comment]
FWIW I favor being extremely liberal in delimiters.  |, for example, is visually quite distinct, and can have the right 'look' in some cases.  Of course, if the strings to be delimited contain ! but not | , then | is a superior choice.  And I can imagine some application which has painted itself into a corner where the only character that is not in a delimited string is '3' is, in which case the digit 3 is the ideal delimiter.  I personally like to have any printable character available as a delimiter, just in case.

**Comment by scottchiefbaker** [comment]
I took an informal poll on #perl and `|` was a popular delimiter. I'm fine if we want to exclude it, but bear in mind it's used in a lot of "real" code.

**Comment by gonzus** [comment]
I think the point here is to restrict this and get back some sanity. I remember seeing code that used `\0` as delimiters... which is great for war stories, but is totally bonkers. I am personally also against `#` because I want my brain to think "comment" when I see a `#`.

FWIW, I personally like using `|` as a delimiter. But I will go along with any *restricted* list that *excludes* crazy shit.

**Comment by xsawyerx** [comment]
> I dunno why but I've always used `|` as an alternate delimiter. it's not a huge deal breaker though. I can switch to `!`.
> 
> Not really clear what this means:
> 
> > I'm not a fan because it's a fairly distance character for non-Perl devs who aren't used to other Perl devs using it

Sorry, this is my poor phrasing.

I meant that, if you're not a Perl developer who saw a different Perl developer use the pipe operator as a delimiter, you wouldn't even think about using it. Of course, this is a presumption on my part.

I'm okay adding the pipe symbol as a delimiter. I'll try to add it this week. (I want to add a bunch of docs and merge other stuff too for a release this weekend.)

**Comment by scottchiefbaker** [comment]
Sounds good. Thank you for being flexible on this issue.

**Comment by xsawyerx** [comment]
Honestly, no reason here for me to be stubborn. The pipe symbol still gives us all we want. Also, I'm not likely to argue a point that is in opposition to both @gonzus and @jeffreykegler. :)

**Comment by xsawyerx** [comment]
PR now available.

**Comment by xsawyerx** [comment]
This is now available in 0.005, on CPAN: https://metacpan.org/pod/standard.

**Comment by scottchiefbaker** [comment]
This is issue is resolved after testing with 0.005.
